### ISSUE TITLE
issues with installing

### ISSUE THREAD

**Issue by Easyschools** [h-mdm/remote-control#28]
I am trying to install it on my server vps and i have tried a lot of different ways and even changed the python version but i have been stuck on this error 

`The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1650318278.32-29226-135942862674728/AnsiballZ_docker_compose.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1650318278.32-29226-135942862674728/AnsiballZ_docker_compose.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1650318278.32-29226-135942862674728/AnsiballZ_docker_compose.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.cloud.docker.docker_compose', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_docker_compose_payload_TuJdks/ansible_docker_compose_payload.zip/ansible/modules/cloud/docker/docker_compose.py", line 476, in <module>
  File "/usr/lib/python2.7/site-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/lib/python2.7/site-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 8, in <module>
    import websocket
  File "/usr/lib/python2.7/site-packages/websocket/__init__.py", line 19, in <module>
    from ._abnf import *
  File "/usr/lib/python2.7/site-packages/websocket/_abnf.py", line 150
    def validate(self, skip_utf8_validation=False) -> None:
                                                   ^
SyntaxError: invalid syntax
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1650318278.32-29226-135942862674728/AnsiballZ_docker_compose.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1650318278.32-29226-135942862674728/AnsiballZ_docker_compose.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1650318278.32-29226-135942862674728/AnsiballZ_docker_compose.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.cloud.docker.docker_compose', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_docker_compose_payload_TuJdks/ansible_docker_compose_payload.zip/ansible/modules/cloud/docker/docker_compose.py\", line 476, in <module>\n  File \"/usr/lib/python2.7/site-packages/docker/__init__.py\", line 2, in <module>\n    from .api import APIClient\n  File \"/usr/lib/python2.7/site-packages/docker/api/__init__.py\", line 2, in <module>\n    from .client import APIClient\n  File \"/usr/lib/python2.7/site-packages/docker/api/client.py\", line 8, in <module>\n   import websocket\n  File \"/usr/lib/python2.7/site-packages/websocket/__init__.py\", line 19, in <module>\n    from ._abnf import *\n  File \"/usr/lib/python2.7/site-packages/websocket/_abnf.py\", line 150\n    def validate(self, skip_utf8_validation=False) -> None:\n                                                   ^\nSyntaxError: invalid syntax\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
`

**Comment by h-mdm** [comment]
You don't need to install Python prior to running the installation script. The script will install the required version itself.

On which Linux do you get the error?

**Comment by Easyschools** [comment]
Centos 7Then why i when i try to install it normally it always gives me error while using python 3
-------- Original message --------From: Headwind MDM ***@***.***> Date: 4/19/22  4:51 AM  (GMT+02:00) To: h-mdm/remote-control ***@***.***> Cc: Easyschools ***@***.***>, Author ***@***.***> Subject: Re: [h-mdm/remote-control] issues with installing (Issue #28) 
You don't need to install Python prior to running the installation script. The script will install the required version itself.
On which Linux do you get the error?

**Comment by h-mdm** [comment]
Unfortunately Headwind Remote isn't compatible with CentOS 7. Consider upgrading to CentOS 8 or using Ubuntu Linux.
